remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Swiss Crypto Day'
email: crypto@inf.unibe.ch
url: 'https://swisscryptoday.github.io/'
description: 'Swiss Crypto Day | A full day of cryptography talks in Switzerland'
twitter_username: cczurich
github_username:  swisscryptoday

future: true
date_format: "%-d %b %Y"

# Set plugins
plugins_dir:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme